name: cursach_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  firebase_ui_auth: ^1.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.6
  iconly: ^1.0.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5

dev_dependencies:
  bloc_test: ^9.1.5
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/lottie/
    - assets/vectors/
